# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TPLINK.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TPLINK(object):
    def setupUi(self, TPLINK):
        TPLINK.setObjectName("TPLINK")
        TPLINK.resize(1125, 622)
        self.layoutWidget = QtWidgets.QWidget(TPLINK)
        self.layoutWidget.setGeometry(QtCore.QRect(840, 0, 271, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.downBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.downBtn.setObjectName("downBtn")
        self.gridLayout.addWidget(self.downBtn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.upBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.upBtn.setObjectName("upBtn")
        self.gridLayout.addWidget(self.upBtn, 0, 1, 1, 1)
        self.rightBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.rightBtn.setObjectName("rightBtn")
        self.gridLayout.addWidget(self.rightBtn, 1, 2, 1, 1)
        self.leftBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.leftBtn.setObjectName("leftBtn")
        self.gridLayout.addWidget(self.leftBtn, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closeBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.snapshotBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.snapshotBtn.setObjectName("snapshotBtn")
        self.horizontalLayout_2.addWidget(self.snapshotBtn)
        self.startRecordBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.startRecordBtn.setObjectName("startRecordBtn")
        self.horizontalLayout_2.addWidget(self.startRecordBtn)
        self.stopRecordBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.stopRecordBtn.setObjectName("stopRecordBtn")
        self.horizontalLayout_2.addWidget(self.stopRecordBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.player = QtWidgets.QLabel(TPLINK)
        self.player.setGeometry(QtCore.QRect(10, 10, 800, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player.sizePolicy().hasHeightForWidth())
        self.player.setSizePolicy(sizePolicy)
        self.player.setMinimumSize(QtCore.QSize(800, 400))
        self.player.setText("")
        self.player.setObjectName("player")

        self.retranslateUi(TPLINK)
        QtCore.QMetaObject.connectSlotsByName(TPLINK)

    def retranslateUi(self, TPLINK):
        _translate = QtCore.QCoreApplication.translate
        TPLINK.setWindowTitle(_translate("TPLINK", "TP-LINK"))
        self.downBtn.setText(_translate("TPLINK", "下"))
        self.upBtn.setText(_translate("TPLINK", "上"))
        self.rightBtn.setText(_translate("TPLINK", "右"))
        self.leftBtn.setText(_translate("TPLINK", "左"))
        self.startBtn.setText(_translate("TPLINK", "开启"))
        self.closeBtn.setText(_translate("TPLINK", "关闭"))
        self.snapshotBtn.setText(_translate("TPLINK", "截屏"))
        self.startRecordBtn.setText(_translate("TPLINK", "开始录制"))
        self.stopRecordBtn.setText(_translate("TPLINK", "停止录制"))
